# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

parameters:
  - name: runCodeAnalysis
    displayName: 'Run code analysis tool'
    type: boolean
    default: true

trigger:
  branches:
    include:
      - main
  paths:
    exclude:
      - README.md
      - logs/*

resources:
  repositories:
    - repository: templates
      type: git
      name: CrossCutting and Innovation/aida-templates
pool: 'Aida'

workspace:
    clean: all

name: $(Date:yy.MM.dd.HHmm)

steps:
- task: UseDotNet@2
  displayName: "Use NetCore 3.1"
  inputs:
    packageType: 'runtime'
    version: '3.1.x'

- task: DotNetCoreCLI@2
  displayName: "Restore"
  inputs:
    command: 'restore'
    projects: 'StringCalculator.sln'
    arguments: "--configuration Release"
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  displayName: "Build"
  inputs:
    command: 'build'
    arguments: "--configuration Release --no-restore"
    projects: 'StringCalculator.sln'

- task: DotNetCoreCLI@2
  displayName: "Test"
  inputs:
    command: 'test'
    arguments: "--configuration Release --no-restore --no-build"
    projects: 'StringCalculator.sln'
- ${{ if parameters.runCodeAnalysis }}:
  - template: ./azuredevops-templates/code-quality-tool-template.yml
    parameters:
      workingDirectory: '$(System.DefaultWorkingDirectory)'
- task: DotNetCoreCLI@2
  displayName: Zip Project
  inputs:
    command: publish
    publishWebProjects: false
    projects: "StringCalculator.Api/StringCalculator.Api.csproj"
    arguments: "-c Release --output $(build.artifactstagingdirectory)"

- task: PublishBuildArtifacts@1
  displayName: Publish