# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  branches:
    include:
    - main
  paths:
    exclude:
    - ./*.md
    - ./.gitignore 

pool: 'Aida'
workspace:
    clean: all
name: $(Date:yy.MM.dd.HHmm)

steps:
- task: UseDotNet@2
  inputs:
    version: '3.1.x'
    packageType: runtime
  displayName: 'Use runtime'

- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    projects: 'StringCalculator.sln'
    feedsToUse: 'select'
  displayName: 'Restore nugget package'
  
- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: 'StringCalculator.sln'
  displayName: 'Build'
- task: DotNetCoreCLI@2
  inputs:
    command: 'test'
    projects: 'StringCalculator.sln'
  displayName: 'Test'

- task: DotNetCoreCLI@2
  inputs:
    command: publish
    publishWebProjects: false
    projects: "StringCalculator.Api/StringCalculator.Api.csproj"
    arguments: "-c Release -r win-x64 --self-contained --output $(build.artifactstagingdirectory)"
  displayName: 'Zip project'
  
- task: PublishBuildArtifacts@1
  displayName: Publish